trigger:
- master

pool:
  name: Lab4

variables:
  buildConfiguration: 'Release'
  platform: 'Any CPU'
  solution: '**/Lab4_Question2.csproj'

steps:

# Optional Cleanup
- task: PowerShell@2
  displayName: 'Clean Temporary Directories'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Cleaning temp folders to avoid disk space issues..."
      Get-ChildItem -Path $env:TEMP -Recurse -Force -ErrorAction SilentlyContinue | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
      Write-Host "Cleanup complete."

# Restore (if applicable)
- task: NuGetToolInstaller@1

# MSBuild Publish
- task: VSBuild@1
  displayName: 'Build and Publish with MSBuild'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:Platform="$(platform)" /target:Publish /p:PublishDir="$(Build.ArtifactStagingDirectory)\\"'
    platform: '$(platform)'
    configuration: '$(buildConfiguration)'

# Publish Artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
