trigger:
- master  # Adjust to your branch name

pool:
  name: Lab4 

steps:
- script: dotnet build --configuration Release
  displayName: 'Build Solution'

- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Application'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
